### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by phil-blain** [phil-blain/CICE#5]
- [x] science guide 
- [x] ~user guide (env files, lapack, etc.)~ pas nécessaire vu que le solveur Anderson sera un *hidden feature* pour commencer
- [x] namelist settings (use_mean_vrel, etc)
- [x] add more references to papers

**Comment by phil-blain** [comment]
@JFLemieux73 j'ai commencé les modifications à la documentation. 
J'ai fait une PR à moi-même pour ce ce soit plus facile pour toi de commenter directement certaines parties : **https://github.com/phil-blain/CICE/pull/35**

Tu peux me donner des commentaires sur la PR ou ici, comme tu préfères.

**Comment by phil-blain** [comment]
Je n'ai pas encore ajouté les settings de namelist.

**Comment by JFLemieux73** [comment]
Ca a l'air correct mais j<ai pas vu les eqs compilées. 

Je remplacerais: 

"There are now different dynamical solvers available in the CICE code." par:

There are different approaches in the CICE code for representing sea ice rheology and for solving the sea ice momentum equation.

**Comment by phil-blain** [comment]
Le lien pour la documentation formatée est dans la PR 35 (j'avoue que c'est subtil que "#35" est un lien : https://cice-phil-blain.readthedocs.io/en/picard-doc/science_guide/sg_dynamics.html

OK je vais faire ce changement pour la 1e phrase.

**Comment by JFLemieux73** [comment]
Ok merci. Peux-tu aussi essayer de régler le problème avec les eqs 3 et 4 pour le evp...elles débordent en html.

**Comment by JFLemieux73** [comment]
Pour Picard k est un subscript et non pas un superscript?.C'est voulu? C'est peut-etre une bonne idée pour le différencier de n pour le time level.

**Comment by phil-blain** [comment]
Oui c'était effectivement pour le différencier du time level.

Oui je vais regarder pour "breaker" les équations 3 et 4.

**Comment by phil-blain** [comment]
![Capture d’écran 2020-07-14 à 15 25 52](https://user-images.githubusercontent.com/44212482/87467852-991a2980-c5e6-11ea-921a-1c2d24164415.png)


trouves-tu que c'est OK comme ça ? je trouve que c'est pas pire... j'aurais préféré un environnement `multline` mais Sphinx semble mettre tous les paragraphes `.. math:` dans un `align` donc ça créé un `multline` dans un `align` et ça ne fait pas le résultat escompté...

**Comment by phil-blain** [comment]
J'ai rajouté des références à différents articles dans 1ce0446 

J'ai rajouté les settings de namelist dans 5fff3858add699065c0847f7ea0028c6aded0553

**Comment by phil-blain** [comment]
@JFLemieux73 as-tu d'autres commentaires sur la doc ? est-ce que tu penses que les papiers/livres que je cite dans le code sont suffisant ? (voir 1ce0446).

**Comment by phil-blain** [comment]
Jugé suffisant.
